brake lights
KaanMol/AGV-1.2 pull request #29
Opened 2021-12-23 10:24 UTC by Quincccy

# Description

lights when braking

Fixes #17 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

With the BoeBot

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-23 12:16 UTC, Daantuk01 commented on src/vehicle/DrivingLights.java
> +        if(this.direction == direction){
spaties bij if en )

2021-12-23 12:16 UTC, Daantuk01 commented on src/vehicle/DrivingLights.java
> +            if(this.backLightsOn == true || this.brakeLightsOn == true) {
spatie bij if

2021-12-23 12:17 UTC, Daantuk01 commented on src/vehicle/DrivingLights.java
> +            if(this.frontLightsOn == true || this.brakeLightsOn == true) {
spatie bij if

2021-12-23 12:18 UTC, Daantuk01 requested changes
spaties bij de if statements

2022-01-07 12:45 UTC, Daantuk01 submitted a review, later dismissed

2022-01-07 12:50 UTC, Momin2004 approved these changes

2022-01-07 12:50 UTC, merged